// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: billing.proto

package modalpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ModalClient_WorkspaceBillingReport_FullMethodName = "/modal.client.ModalClient/WorkspaceBillingReport"
)

// ModalClientClient is the client API for ModalClient service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ModalClientClient interface {
	WorkspaceBillingReport(ctx context.Context, in *WorkspaceBillingReportRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorkspaceBillingReportItem], error)
}

type modalClientClient struct {
	cc grpc.ClientConnInterface
}

func NewModalClientClient(cc grpc.ClientConnInterface) ModalClientClient {
	return &modalClientClient{cc}
}

func (c *modalClientClient) WorkspaceBillingReport(ctx context.Context, in *WorkspaceBillingReportRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorkspaceBillingReportItem], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ModalClient_ServiceDesc.Streams[0], ModalClient_WorkspaceBillingReport_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WorkspaceBillingReportRequest, WorkspaceBillingReportItem]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ModalClient_WorkspaceBillingReportClient = grpc.ServerStreamingClient[WorkspaceBillingReportItem]

// ModalClientServer is the server API for ModalClient service.
// All implementations must embed UnimplementedModalClientServer
// for forward compatibility.
type ModalClientServer interface {
	WorkspaceBillingReport(*WorkspaceBillingReportRequest, grpc.ServerStreamingServer[WorkspaceBillingReportItem]) error
	mustEmbedUnimplementedModalClientServer()
}

// UnimplementedModalClientServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModalClientServer struct{}

func (UnimplementedModalClientServer) WorkspaceBillingReport(*WorkspaceBillingReportRequest, grpc.ServerStreamingServer[WorkspaceBillingReportItem]) error {
	return status.Error(codes.Unimplemented, "method WorkspaceBillingReport not implemented")
}
func (UnimplementedModalClientServer) mustEmbedUnimplementedModalClientServer() {}
func (UnimplementedModalClientServer) testEmbeddedByValue()                     {}

// UnsafeModalClientServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModalClientServer will
// result in compilation errors.
type UnsafeModalClientServer interface {
	mustEmbedUnimplementedModalClientServer()
}

func RegisterModalClientServer(s grpc.ServiceRegistrar, srv ModalClientServer) {
	// If the following call panics, it indicates UnimplementedModalClientServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModalClient_ServiceDesc, srv)
}

func _ModalClient_WorkspaceBillingReport_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WorkspaceBillingReportRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ModalClientServer).WorkspaceBillingReport(m, &grpc.GenericServerStream[WorkspaceBillingReportRequest, WorkspaceBillingReportItem]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ModalClient_WorkspaceBillingReportServer = grpc.ServerStreamingServer[WorkspaceBillingReportItem]

// ModalClient_ServiceDesc is the grpc.ServiceDesc for ModalClient service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModalClient_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "modal.client.ModalClient",
	HandlerType: (*ModalClientServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WorkspaceBillingReport",
			Handler:       _ModalClient_WorkspaceBillingReport_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "billing.proto",
}
