// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: billing.proto

package modalpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkspaceBillingReportItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ObjectId        string                 `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	Description     string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	EnvironmentName string                 `protobuf:"bytes,3,opt,name=environment_name,json=environmentName,proto3" json:"environment_name,omitempty"`
	Interval        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=interval,proto3" json:"interval,omitempty"`
	Cost            string                 `protobuf:"bytes,5,opt,name=cost,proto3" json:"cost,omitempty"`
	Tags            map[string]string      `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CostByResource  map[string]string      `protobuf:"bytes,8,rep,name=cost_by_resource,json=costByResource,proto3" json:"cost_by_resource,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WorkspaceBillingReportItem) Reset() {
	*x = WorkspaceBillingReportItem{}
	mi := &file_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceBillingReportItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceBillingReportItem) ProtoMessage() {}

func (x *WorkspaceBillingReportItem) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceBillingReportItem.ProtoReflect.Descriptor instead.
func (*WorkspaceBillingReportItem) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{0}
}

func (x *WorkspaceBillingReportItem) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *WorkspaceBillingReportItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WorkspaceBillingReportItem) GetEnvironmentName() string {
	if x != nil {
		return x.EnvironmentName
	}
	return ""
}

func (x *WorkspaceBillingReportItem) GetInterval() *timestamppb.Timestamp {
	if x != nil {
		return x.Interval
	}
	return nil
}

func (x *WorkspaceBillingReportItem) GetCost() string {
	if x != nil {
		return x.Cost
	}
	return ""
}

func (x *WorkspaceBillingReportItem) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *WorkspaceBillingReportItem) GetCostByResource() map[string]string {
	if x != nil {
		return x.CostByResource
	}
	return nil
}

type WorkspaceBillingReportRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StartTimestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_timestamp,json=startTimestamp,proto3" json:"start_timestamp,omitempty"`
	EndTimestamp   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_timestamp,json=endTimestamp,proto3" json:"end_timestamp,omitempty"`
	Resolution     string                 `protobuf:"bytes,3,opt,name=resolution,proto3" json:"resolution,omitempty"`
	TagNames       []string               `protobuf:"bytes,4,rep,name=tag_names,json=tagNames,proto3" json:"tag_names,omitempty"`
	EnvironmentIds []string               `protobuf:"bytes,5,rep,name=environment_ids,json=environmentIds,proto3" json:"environment_ids,omitempty"`
	AppIds         []string               `protobuf:"bytes,6,rep,name=app_ids,json=appIds,proto3" json:"app_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WorkspaceBillingReportRequest) Reset() {
	*x = WorkspaceBillingReportRequest{}
	mi := &file_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceBillingReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceBillingReportRequest) ProtoMessage() {}

func (x *WorkspaceBillingReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceBillingReportRequest.ProtoReflect.Descriptor instead.
func (*WorkspaceBillingReportRequest) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{1}
}

func (x *WorkspaceBillingReportRequest) GetStartTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTimestamp
	}
	return nil
}

func (x *WorkspaceBillingReportRequest) GetEndTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTimestamp
	}
	return nil
}

func (x *WorkspaceBillingReportRequest) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

func (x *WorkspaceBillingReportRequest) GetTagNames() []string {
	if x != nil {
		return x.TagNames
	}
	return nil
}

func (x *WorkspaceBillingReportRequest) GetEnvironmentIds() []string {
	if x != nil {
		return x.EnvironmentIds
	}
	return nil
}

func (x *WorkspaceBillingReportRequest) GetAppIds() []string {
	if x != nil {
		return x.AppIds
	}
	return nil
}

type WorkspaceBillingSummaryRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StartTimestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_timestamp,json=startTimestamp,proto3" json:"start_timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WorkspaceBillingSummaryRequest) Reset() {
	*x = WorkspaceBillingSummaryRequest{}
	mi := &file_billing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceBillingSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceBillingSummaryRequest) ProtoMessage() {}

func (x *WorkspaceBillingSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceBillingSummaryRequest.ProtoReflect.Descriptor instead.
func (*WorkspaceBillingSummaryRequest) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{2}
}

func (x *WorkspaceBillingSummaryRequest) GetStartTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTimestamp
	}
	return nil
}

type WorkspaceBillingSummaryResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	StartTimestamp       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_timestamp,json=startTimestamp,proto3" json:"start_timestamp,omitempty"`
	EndTimestamp         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_timestamp,json=endTimestamp,proto3" json:"end_timestamp,omitempty"`
	MeteredCost          string                 `protobuf:"bytes,3,opt,name=metered_cost,json=meteredCost,proto3" json:"metered_cost,omitempty"`
	BilledCost           string                 `protobuf:"bytes,4,opt,name=billed_cost,json=billedCost,proto3" json:"billed_cost,omitempty"`
	MeteredCostBreakdown map[string]string      `protobuf:"bytes,5,rep,name=metered_cost_breakdown,json=meteredCostBreakdown,proto3" json:"metered_cost_breakdown,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Adjustments          map[string]string      `protobuf:"bytes,6,rep,name=adjustments,proto3" json:"adjustments,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *WorkspaceBillingSummaryResponse) Reset() {
	*x = WorkspaceBillingSummaryResponse{}
	mi := &file_billing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceBillingSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceBillingSummaryResponse) ProtoMessage() {}

func (x *WorkspaceBillingSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceBillingSummaryResponse.ProtoReflect.Descriptor instead.
func (*WorkspaceBillingSummaryResponse) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{3}
}

func (x *WorkspaceBillingSummaryResponse) GetStartTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTimestamp
	}
	return nil
}

func (x *WorkspaceBillingSummaryResponse) GetEndTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTimestamp
	}
	return nil
}

func (x *WorkspaceBillingSummaryResponse) GetMeteredCost() string {
	if x != nil {
		return x.MeteredCost
	}
	return ""
}

func (x *WorkspaceBillingSummaryResponse) GetBilledCost() string {
	if x != nil {
		return x.BilledCost
	}
	return ""
}

func (x *WorkspaceBillingSummaryResponse) GetMeteredCostBreakdown() map[string]string {
	if x != nil {
		return x.MeteredCostBreakdown
	}
	return nil
}

func (x *WorkspaceBillingSummaryResponse) GetAdjustments() map[string]string {
	if x != nil {
		return x.Adjustments
	}
	return nil
}

var File_billing_proto protoreflect.FileDescriptor

const file_billing_proto_rawDesc = "" +
	"\n" +
	"\rbilling.proto\x12\fmodal.client\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfe\x03\n" +
	"\x1aWorkspaceBillingReportItem\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\tR\bobjectId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12)\n" +
	"\x10environment_name\x18\x03 \x01(\tR\x0fenvironmentName\x126\n" +
	"\binterval\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\binterval\x12\x12\n" +
	"\x04cost\x18\x05 \x01(\tR\x04cost\x12F\n" +
	"\x04tags\x18\x06 \x03(\v22.modal.client.WorkspaceBillingReportItem.TagsEntryR\x04tags\x12f\n" +
	"\x10cost_by_resource\x18\b \x03(\v2<.modal.client.WorkspaceBillingReportItem.CostByResourceEntryR\x0ecostByResource\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aA\n" +
	"\x13CostByResourceEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa4\x02\n" +
	"\x1dWorkspaceBillingReportRequest\x12C\n" +
	"\x0fstart_timestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x0estartTimestamp\x12?\n" +
	"\rend_timestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\fendTimestamp\x12\x1e\n" +
	"\n" +
	"resolution\x18\x03 \x01(\tR\n" +
	"resolution\x12\x1b\n" +
	"\ttag_names\x18\x04 \x03(\tR\btagNames\x12'\n" +
	"\x0fenvironment_ids\x18\x05 \x03(\tR\x0eenvironmentIds\x12\x17\n" +
	"\aapp_ids\x18\x06 \x03(\tR\x06appIds\"e\n" +
	"\x1eWorkspaceBillingSummaryRequest\x12C\n" +
	"\x0fstart_timestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x0estartTimestamp\"\xd5\x04\n" +
	"\x1fWorkspaceBillingSummaryResponse\x12C\n" +
	"\x0fstart_timestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x0estartTimestamp\x12?\n" +
	"\rend_timestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\fendTimestamp\x12!\n" +
	"\fmetered_cost\x18\x03 \x01(\tR\vmeteredCost\x12\x1f\n" +
	"\vbilled_cost\x18\x04 \x01(\tR\n" +
	"billedCost\x12}\n" +
	"\x16metered_cost_breakdown\x18\x05 \x03(\v2G.modal.client.WorkspaceBillingSummaryResponse.MeteredCostBreakdownEntryR\x14meteredCostBreakdown\x12`\n" +
	"\vadjustments\x18\x06 \x03(\v2>.modal.client.WorkspaceBillingSummaryResponse.AdjustmentsEntryR\vadjustments\x1aG\n" +
	"\x19MeteredCostBreakdownEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AdjustmentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xf8\x01\n" +
	"\vModalClient\x12q\n" +
	"\x16WorkspaceBillingReport\x12+.modal.client.WorkspaceBillingReportRequest\x1a(.modal.client.WorkspaceBillingReportItem0\x01\x12v\n" +
	"\x17WorkspaceBillingSummary\x12,.modal.client.WorkspaceBillingSummaryRequest\x1a-.modal.client.WorkspaceBillingSummaryResponseBEZCgithub.com/baselinehq/focus-exporter/pkg/integrations/modal/modalpbb\x06proto3"

var (
	file_billing_proto_rawDescOnce sync.Once
	file_billing_proto_rawDescData []byte
)

func file_billing_proto_rawDescGZIP() []byte {
	file_billing_proto_rawDescOnce.Do(func() {
		file_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_billing_proto_rawDesc), len(file_billing_proto_rawDesc)))
	})
	return file_billing_proto_rawDescData
}

var file_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_billing_proto_goTypes = []any{
	(*WorkspaceBillingReportItem)(nil),      // 0: modal.client.WorkspaceBillingReportItem
	(*WorkspaceBillingReportRequest)(nil),   // 1: modal.client.WorkspaceBillingReportRequest
	(*WorkspaceBillingSummaryRequest)(nil),  // 2: modal.client.WorkspaceBillingSummaryRequest
	(*WorkspaceBillingSummaryResponse)(nil), // 3: modal.client.WorkspaceBillingSummaryResponse
	nil,                                     // 4: modal.client.WorkspaceBillingReportItem.TagsEntry
	nil,                                     // 5: modal.client.WorkspaceBillingReportItem.CostByResourceEntry
	nil,                                     // 6: modal.client.WorkspaceBillingSummaryResponse.MeteredCostBreakdownEntry
	nil,                                     // 7: modal.client.WorkspaceBillingSummaryResponse.AdjustmentsEntry
	(*timestamppb.Timestamp)(nil),           // 8: google.protobuf.Timestamp
}
var file_billing_proto_depIdxs = []int32{
	8,  // 0: modal.client.WorkspaceBillingReportItem.interval:type_name -> google.protobuf.Timestamp
	4,  // 1: modal.client.WorkspaceBillingReportItem.tags:type_name -> modal.client.WorkspaceBillingReportItem.TagsEntry
	5,  // 2: modal.client.WorkspaceBillingReportItem.cost_by_resource:type_name -> modal.client.WorkspaceBillingReportItem.CostByResourceEntry
	8,  // 3: modal.client.WorkspaceBillingReportRequest.start_timestamp:type_name -> google.protobuf.Timestamp
	8,  // 4: modal.client.WorkspaceBillingReportRequest.end_timestamp:type_name -> google.protobuf.Timestamp
	8,  // 5: modal.client.WorkspaceBillingSummaryRequest.start_timestamp:type_name -> google.protobuf.Timestamp
	8,  // 6: modal.client.WorkspaceBillingSummaryResponse.start_timestamp:type_name -> google.protobuf.Timestamp
	8,  // 7: modal.client.WorkspaceBillingSummaryResponse.end_timestamp:type_name -> google.protobuf.Timestamp
	6,  // 8: modal.client.WorkspaceBillingSummaryResponse.metered_cost_breakdown:type_name -> modal.client.WorkspaceBillingSummaryResponse.MeteredCostBreakdownEntry
	7,  // 9: modal.client.WorkspaceBillingSummaryResponse.adjustments:type_name -> modal.client.WorkspaceBillingSummaryResponse.AdjustmentsEntry
	1,  // 10: modal.client.ModalClient.WorkspaceBillingReport:input_type -> modal.client.WorkspaceBillingReportRequest
	2,  // 11: modal.client.ModalClient.WorkspaceBillingSummary:input_type -> modal.client.WorkspaceBillingSummaryRequest
	0,  // 12: modal.client.ModalClient.WorkspaceBillingReport:output_type -> modal.client.WorkspaceBillingReportItem
	3,  // 13: modal.client.ModalClient.WorkspaceBillingSummary:output_type -> modal.client.WorkspaceBillingSummaryResponse
	12, // [12:14] is the sub-list for method output_type
	10, // [10:12] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_billing_proto_init() }
func file_billing_proto_init() {
	if File_billing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_billing_proto_rawDesc), len(file_billing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_billing_proto_goTypes,
		DependencyIndexes: file_billing_proto_depIdxs,
		MessageInfos:      file_billing_proto_msgTypes,
	}.Build()
	File_billing_proto = out.File
	file_billing_proto_goTypes = nil
	file_billing_proto_depIdxs = nil
}
