// Code generated by internal/gen. DO NOT EDIT.

package focus

import (
	"encoding/json"
	"time"
)

type Record struct {
	BilledCost                         string           `json:"BilledCost"`
	EffectiveCost                      string           `json:"EffectiveCost"`
	ListCost                           string           `json:"ListCost"`
	ContractedCost                     string           `json:"ContractedCost"`
	BillingAccountId                   string           `json:"BillingAccountId"`
	BillingCurrency                    string           `json:"BillingCurrency"`
	BillingPeriodStart                 time.Time        `json:"BillingPeriodStart"`
	BillingPeriodEnd                   time.Time        `json:"BillingPeriodEnd"`
	ChargeCategory                     string           `json:"ChargeCategory"`
	ChargePeriodStart                  time.Time        `json:"ChargePeriodStart"`
	ChargePeriodEnd                    time.Time        `json:"ChargePeriodEnd"`
	ServiceName                        string           `json:"ServiceName"`
	Provider                           string           `json:"Provider"`
	AvailabilityZone                   *string          `json:"AvailabilityZone,omitempty"`
	BillingAccountName                 *string          `json:"BillingAccountName,omitempty"`
	BillingAccountType                 *string          `json:"BillingAccountType,omitempty"`
	CapacityReservationId              *string          `json:"CapacityReservationId,omitempty"`
	CapacityReservationStatus          *string          `json:"CapacityReservationStatus,omitempty"`
	ChargeClass                        *string          `json:"ChargeClass,omitempty"`
	ChargeDescription                  *string          `json:"ChargeDescription,omitempty"`
	ChargeFrequency                    *string          `json:"ChargeFrequency,omitempty"`
	CommitmentDiscountCategory         *string          `json:"CommitmentDiscountCategory,omitempty"`
	CommitmentDiscountId               *string          `json:"CommitmentDiscountId,omitempty"`
	CommitmentDiscountName             *string          `json:"CommitmentDiscountName,omitempty"`
	CommitmentDiscountQuantity         *string          `json:"CommitmentDiscountQuantity,omitempty"`
	CommitmentDiscountStatus           *string          `json:"CommitmentDiscountStatus,omitempty"`
	CommitmentDiscountType             *string          `json:"CommitmentDiscountType,omitempty"`
	CommitmentDiscountUnit             *string          `json:"CommitmentDiscountUnit,omitempty"`
	ConsumedQuantity                   *string          `json:"ConsumedQuantity,omitempty"`
	ConsumedUnit                       *string          `json:"ConsumedUnit,omitempty"`
	ContractedUnitPrice                *string          `json:"ContractedUnitPrice,omitempty"`
	InvoiceId                          *string          `json:"InvoiceId,omitempty"`
	InvoiceIssuer                      *string          `json:"InvoiceIssuer,omitempty"`
	ListUnitPrice                      *string          `json:"ListUnitPrice,omitempty"`
	PricingCategory                    *string          `json:"PricingCategory,omitempty"`
	PricingCurrency                    *string          `json:"PricingCurrency,omitempty"`
	PricingCurrencyContractedUnitPrice *string          `json:"PricingCurrencyContractedUnitPrice,omitempty"`
	PricingCurrencyEffectiveCost       *string          `json:"PricingCurrencyEffectiveCost,omitempty"`
	PricingCurrencyListUnitPrice       *string          `json:"PricingCurrencyListUnitPrice,omitempty"`
	PricingQuantity                    *string          `json:"PricingQuantity,omitempty"`
	PricingUnit                        *string          `json:"PricingUnit,omitempty"`
	Publisher                          *string          `json:"Publisher,omitempty"`
	RegionId                           *string          `json:"RegionId,omitempty"`
	RegionName                         *string          `json:"RegionName,omitempty"`
	ResourceId                         *string          `json:"ResourceId,omitempty"`
	ResourceName                       *string          `json:"ResourceName,omitempty"`
	ResourceType                       *string          `json:"ResourceType,omitempty"`
	ServiceCategory                    *string          `json:"ServiceCategory,omitempty"`
	ServiceSubcategory                 *string          `json:"ServiceSubcategory,omitempty"`
	SkuId                              *string          `json:"SkuId,omitempty"`
	SkuMeter                           *string          `json:"SkuMeter,omitempty"`
	SkuPriceId                         *string          `json:"SkuPriceId,omitempty"`
	SkuPriceDetails                    *json.RawMessage `json:"SkuPriceDetails,omitempty"`
	SubAccountId                       *string          `json:"SubAccountId,omitempty"`
	SubAccountName                     *string          `json:"SubAccountName,omitempty"`
	SubAccountType                     *string          `json:"SubAccountType,omitempty"`
	Tags                               *json.RawMessage `json:"Tags,omitempty"`

	Extensions map[string]any `json:"-"`
}
